In [34]:
import numpy as np

In [35]:
a1 = np.array([1,5,9,6])

In [36]:
print a1

[1 5 9 6]


In [37]:
a1

array([1, 5, 9, 6])

In [38]:
print type(a1)

<type 'numpy.ndarray'>


In [39]:
a1.dtype

dtype('int32')

In [40]:
a1 = np.array([1,5,9,6.])
a1.dtype

dtype('float64')

In [41]:
a1 = np.array([1,5,9,6],dtype = np.float64)
a1.dtype

dtype('float64')

In [42]:
a2 = np.arange(30).reshape(3,10)

In [43]:
a2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [44]:
a2.ndim

2

In [45]:
a2.size

30

In [46]:
a2.shape

(3, 10)

In [47]:
print "Sum of a1 : ",a1.sum()
print "Sum of a2 : ",a2.sum()

Sum of a1 :  21.0
Sum of a2 :  435


In [48]:
print np.min(a1)
print np.min(a2)

1.0
0


In [49]:
print "Row-wise sum : ", np.sum(a2,axis=1)
print "Column-wise sum : ", np.sum(a2,axis=0)

Row-wise sum :  [ 45 145 245]
Column-wise sum :  [30 33 36 39 42 45 48 51 54 57]


In [50]:
 np.mean(a2)

14.5

In [51]:
print "Row-wise mean : ",np.mean(a2,axis=1)
print "Column-wise mean : ",np.mean(a2,axis=0)

Row-wise mean :  [ 4.5 14.5 24.5]
Column-wise mean :  [10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]


In [52]:
np.sqrt(a2)

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
        2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ],
       [3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
        3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894],
       [4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949,
        5.        , 5.09901951, 5.19615242, 5.29150262, 5.38516481]])

In [53]:
print "Simple variance",np.var(a2)

Simple variance 74.91666666666667


In [54]:
print "Row-wise variance",np.var(a2,axis=1)
print "Column-wise variance",np.var(a2,axis=0)

Row-wise variance [8.25 8.25 8.25]
Column-wise variance [66.66666667 66.66666667 66.66666667 66.66666667 66.66666667 66.66666667
 66.66666667 66.66666667 66.66666667 66.66666667]


In [55]:
np.log10(a2[1:])

array([[1.        , 1.04139269, 1.07918125, 1.11394335, 1.14612804,
        1.17609126, 1.20411998, 1.23044892, 1.25527251, 1.2787536 ],
       [1.30103   , 1.32221929, 1.34242268, 1.36172784, 1.38021124,
        1.39794001, 1.41497335, 1.43136376, 1.44715803, 1.462398  ]])

In [56]:
a3 = np.random.random((3,4))

In [57]:
a3 = a3*10

In [58]:
a3

array([[6.88570752, 3.16712673, 7.40156455, 9.59204981],
       [8.98470114, 9.95367645, 8.48662844, 1.04179824],
       [1.87203007, 6.00778712, 9.60371419, 3.53406208]])

In [59]:
a3[1,2]

8.48662843964777

In [60]:
intOfa3 = np.int16(a3)

In [61]:
intOfa3

array([[6, 3, 7, 9],
       [8, 9, 8, 1],
       [1, 6, 9, 3]], dtype=int16)

In [62]:
intOfa3.sort(axis = 1)
intOfa3

array([[3, 6, 7, 9],
       [1, 8, 8, 9],
       [1, 3, 6, 9]], dtype=int16)

In [63]:
a4 = np.arange(9,dtype=np.float16).reshape(3,3)
a4

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]], dtype=float16)

In [64]:
a5 = np.linspace(1,10,20).reshape(5,4)
a5

array([[ 1.        ,  1.47368421,  1.94736842,  2.42105263],
       [ 2.89473684,  3.36842105,  3.84210526,  4.31578947],
       [ 4.78947368,  5.26315789,  5.73684211,  6.21052632],
       [ 6.68421053,  7.15789474,  7.63157895,  8.10526316],
       [ 8.57894737,  9.05263158,  9.52631579, 10.        ]])

In [65]:
a6 = np.zeros((5,5))
a6.fill(7)
a6

array([[7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.]])

In [66]:
a7 = a6.reshape(a6.size)
print a7
print a7.size

[7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7.
 7.]
25


In [72]:
a8 = a6.ravel()
a8.size

25

In [77]:
np.hstack(a3)

array([6.88570752, 3.16712673, 7.40156455, 9.59204981, 8.98470114,
       9.95367645, 8.48662844, 1.04179824, 1.87203007, 6.00778712,
       9.60371419, 3.53406208])

In [80]:
matrix1 = np.random.random(12).reshape(3,4)
matrix2 = np.random.random(12).reshape(4,3)
matrix1*=10
matrix2*=10

In [83]:
matrix1

array([[9.25520963, 2.92828793, 7.60782291, 8.41155256],
       [5.50925931, 2.11614056, 1.69548033, 0.1633341 ],
       [3.14228361, 1.78424113, 4.9142981 , 2.89673896]])

In [84]:
matrix2

array([[4.92847589, 3.21310451, 4.26534756],
       [6.02888207, 7.64870412, 1.3552572 ],
       [7.70880016, 4.3772739 , 9.12261228],
       [9.93416682, 9.23643396, 4.57227234]])

In [85]:
np.dot(matrix1,matrix2)

array([[205.47733285, 163.12983813, 151.30839688],
       [ 54.60292076,  42.81776536,  42.58083817],
       [ 92.9036784 ,  72.01038505,  73.89695297]])